[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "ai-content-optimizer"

[services.variables]
PORT = "8080"
FLASK_ENV = "production"
